springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}

spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}

  flyway:
    schemas: ${FLYWAY_SCHEMAS:game_api}
